
package gym_management_system;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rushabh Warke
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    Connection con=null;
    ResultSet rs=null;
    PreparedStatement ps=null;
    String clientName, mobile, clientId, Gender;
    
    DefaultTableModel model; 
    
    
    public HomePage() {
        initComponents();
         con=DBconnection.getconnection();
        setClientDetails();
        int coachId = setDataToCard1();
        lbl_noOfTrainers.setText(Integer.toString(coachId));
        int clientId = setDataToCard2();
        lbl_noOfClients.setText(Integer.toString(clientId));
    }
   public void setClientDetails(){
        try
        {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM `client_details`");

            while(rs.next())
            {
                int clientId = rs.getInt("client_id");
                String clientName = rs.getString("client_name");
                String mobile = rs.getString("mobile");
                String Gender = rs.getString("gender");

                Object[] obj = {clientId, clientName, mobile, Gender};
                model = (DefaultTableModel)ClientTable.getModel();
                model.addRow(obj);

            }
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }
    
    public int setDataToCard1()
    {
        int coachId = 0;
        try 
        {
           PreparedStatement pst = con.prepareStatement("select max(coach_id) from coach_details");
            ResultSet rs = pst.executeQuery();
            
            if(rs.next())
            {
                coachId = rs.getInt("max(coach_id)");
            }
        } 
        catch (Exception e) 
        {
            e.printStackTrace();
        }
        return coachId;
    }
    
    public int setDataToCard2()
    {
        int clientId = 0;
        try 
        {
           PreparedStatement pst = con.prepareStatement("select max(client_Id) from client_details");
            ResultSet rs = pst.executeQuery();
            
            if(rs.next())
            {
                clientId = rs.getInt("max(client_Id)");
            }
        } 
        catch (Exception e) 
        {
            e.printStackTrace();
        }
        return clientId;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pnl_defaulterList = new javax.swing.JPanel();
        lbl_defaulterList = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        pnl_manageCoaches = new javax.swing.JPanel();
        lbl_manageCoaches = new javax.swing.JLabel();
        pnl_manageClients = new javax.swing.JPanel();
        lbl_manageClients = new javax.swing.JLabel();
        pnl_exit = new javax.swing.JPanel();
        lbl_exit = new javax.swing.JLabel();
        pnl_allocateTrainers = new javax.swing.JPanel();
        lbl_allocateTrainers = new javax.swing.JLabel();
        pnl_viewRecord = new javax.swing.JPanel();
        lbl_viewRecord = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        lbl_noOfClients = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        lbl_noOfTrainers = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ClientTable = new javax.swing.JTable();
        btn6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym_management_system/adminIcons/adminIcons/icons8_menu_48px_1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 50, 30));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 5, 50));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym_management_system/adminIcons/adminIcons/male_user_50px.png"))); // NOI18N
        jLabel2.setText("Welcome, Admin");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("GYM Management System");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 25, -1, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("X");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 10, 20, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, 70));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 102, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym_management_system/adminIcons/adminIcons/icons8_Home_26px_2.png"))); // NOI18N
        jLabel5.setText("     Home Page");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 340, 60));

        pnl_defaulterList.setBackground(new java.awt.Color(51, 51, 51));
        pnl_defaulterList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_defaulterListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_defaulterListMouseExited(evt);
            }
        });
        pnl_defaulterList.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_defaulterList.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        lbl_defaulterList.setForeground(new java.awt.Color(255, 255, 255));
        lbl_defaulterList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gym (2).png"))); // NOI18N
        lbl_defaulterList.setText("   Defaulter List ");
        lbl_defaulterList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_defaulterListMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_defaulterListMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_defaulterListMouseExited(evt);
            }
        });
        pnl_defaulterList.add(lbl_defaulterList, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 15, -1, -1));

        jPanel3.add(pnl_defaulterList, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 340, 60));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Features");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("   GMS Dashboard ");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 15, -1, -1));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 340, 60));

        pnl_manageCoaches.setBackground(new java.awt.Color(51, 51, 51));
        pnl_manageCoaches.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_manageCoachesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_manageCoachesMouseExited(evt);
            }
        });
        pnl_manageCoaches.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_manageCoaches.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        lbl_manageCoaches.setForeground(new java.awt.Color(255, 255, 255));
        lbl_manageCoaches.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gym (2).png"))); // NOI18N
        lbl_manageCoaches.setText("   Manage Coaches");
        lbl_manageCoaches.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_manageCoachesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_manageCoachesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_manageCoachesMouseExited(evt);
            }
        });
        pnl_manageCoaches.add(lbl_manageCoaches, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 15, -1, -1));

        jPanel3.add(pnl_manageCoaches, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 340, 60));

        pnl_manageClients.setBackground(new java.awt.Color(51, 51, 51));
        pnl_manageClients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_manageClientsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_manageClientsMouseExited(evt);
            }
        });
        pnl_manageClients.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_manageClients.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        lbl_manageClients.setForeground(new java.awt.Color(255, 255, 255));
        lbl_manageClients.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gym (2).png"))); // NOI18N
        lbl_manageClients.setText("   Manage Clients ");
        lbl_manageClients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_manageClientsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_manageClientsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_manageClientsMouseExited(evt);
            }
        });
        pnl_manageClients.add(lbl_manageClients, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 15, -1, -1));

        jPanel3.add(pnl_manageClients, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 340, 60));

        pnl_exit.setBackground(new java.awt.Color(51, 51, 51));
        pnl_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_exitMouseExited(evt);
            }
        });
        pnl_exit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_exit.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        lbl_exit.setForeground(new java.awt.Color(255, 255, 255));
        lbl_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym_management_system/adminIcons/adminIcons/icons8_Exit_26px_2.png"))); // NOI18N
        lbl_exit.setText("     Exit");
        lbl_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_exitMouseExited(evt);
            }
        });
        pnl_exit.add(lbl_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 15, -1, -1));

        jPanel3.add(pnl_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 340, 60));

        pnl_allocateTrainers.setBackground(new java.awt.Color(51, 51, 51));
        pnl_allocateTrainers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_allocateTrainersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_allocateTrainersMouseExited(evt);
            }
        });
        pnl_allocateTrainers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_allocateTrainers.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        lbl_allocateTrainers.setForeground(new java.awt.Color(255, 255, 255));
        lbl_allocateTrainers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gym (2).png"))); // NOI18N
        lbl_allocateTrainers.setText("   Allocate Trainers ");
        lbl_allocateTrainers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_allocateTrainersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_allocateTrainersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_allocateTrainersMouseExited(evt);
            }
        });
        pnl_allocateTrainers.add(lbl_allocateTrainers, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 15, -1, -1));

        jPanel3.add(pnl_allocateTrainers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 340, 60));

        pnl_viewRecord.setBackground(new java.awt.Color(51, 51, 51));
        pnl_viewRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnl_viewRecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnl_viewRecordMouseExited(evt);
            }
        });
        pnl_viewRecord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_viewRecord.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        lbl_viewRecord.setForeground(new java.awt.Color(255, 255, 255));
        lbl_viewRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gym (2).png"))); // NOI18N
        lbl_viewRecord.setText("   View Records ");
        lbl_viewRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_viewRecordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_viewRecordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_viewRecordMouseExited(evt);
            }
        });
        pnl_viewRecord.add(lbl_viewRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 15, -1, -1));

        jPanel3.add(pnl_viewRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 340, 60));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 340, 750));

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 1, 1, 1, new java.awt.Color(255, 51, 51)));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_noOfClients.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lbl_noOfClients.setForeground(new java.awt.Color(102, 102, 102));
        lbl_noOfClients.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym_management_system/adminIcons/adminIcons/icons8_People_50px.png"))); // NOI18N
        lbl_noOfClients.setText("  7");
        jPanel16.add(lbl_noOfClients, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        getContentPane().add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 260, 140));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Client Details");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("No. of Trainers");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 100, -1, -1));

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 1, 1, 1, new java.awt.Color(255, 51, 51)));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_noOfTrainers.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lbl_noOfTrainers.setForeground(new java.awt.Color(102, 102, 102));
        lbl_noOfTrainers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym_management_system/adminIcons/adminIcons/icons8_People_50px.png"))); // NOI18N
        lbl_noOfTrainers.setText("  7");
        jPanel17.add(lbl_noOfTrainers, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        getContentPane().add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, 260, 140));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 102, 102));
        jLabel24.setText("No. of Clients");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, -1, -1));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1008, 130, -1, 560));

        jScrollPane1.setBackground(new java.awt.Color(255, 153, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));

        ClientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Prathamesh", "8624975041", "Male"},
                {"2", "Mandar", "9875421364", "Male"},
                {"3", "Suraj", "7458962143", "Male"},
                {"4", "Mohish", "7896541230", "Male"},
                {"5", "Ajinkya", "4789512547", "Male"},
                {"6", "Aditya", "9856041237", "Male"},
                {"7", "Utkarsh", "9632587410", "Male"},
                {"8", "Yash", "9514782360", "Male"},
                {"9", "Paras", "9713546280", "Male"},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Mobile", "Gender"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ClientTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClientTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ClientTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 620, 280));

        btn6.setBackground(new java.awt.Color(0, 0, 104));
        btn6.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        btn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn6MouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Log Out");

        javax.swing.GroupLayout btn6Layout = new javax.swing.GroupLayout(btn6);
        btn6.setLayout(btn6Layout);
        btn6Layout.setHorizontalGroup(
            btn6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addContainerGap())
        );
        btn6Layout.setVerticalGroup(
            btn6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 730, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSMaterialButtonRectangle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_rSMaterialButtonRectangle1ActionPerformed

    private void lbl_manageCoachesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_manageCoachesMouseClicked
        ManageCoaches mc = new ManageCoaches();
        mc.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_manageCoachesMouseClicked

    private void lbl_manageCoachesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_manageCoachesMouseEntered
        Color clr = new Color(255, 51, 51);
        pnl_manageCoaches.setBackground(clr);
    }//GEN-LAST:event_lbl_manageCoachesMouseEntered

    private void lbl_manageCoachesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_manageCoachesMouseExited
        Color clr = new Color(51,51,51);
        pnl_manageCoaches.setBackground(clr);
    }//GEN-LAST:event_lbl_manageCoachesMouseExited

    private void pnl_manageCoachesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_manageCoachesMouseEntered
        Color clr = new Color(255,51,51);
        pnl_manageCoaches.setBackground(clr);
    }//GEN-LAST:event_pnl_manageCoachesMouseEntered

    private void pnl_manageCoachesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_manageCoachesMouseExited
        Color clr = new Color(51,51,51);
        pnl_manageCoaches.setBackground(clr);
    }//GEN-LAST:event_pnl_manageCoachesMouseExited

    private void lbl_manageClientsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_manageClientsMouseEntered
        Color clr = new Color(255, 51, 51);
        pnl_manageClients.setBackground(clr);
    }//GEN-LAST:event_lbl_manageClientsMouseEntered

    private void lbl_manageClientsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_manageClientsMouseExited
        Color clr = new Color(51,51,51);
        pnl_manageClients.setBackground(clr);
    }//GEN-LAST:event_lbl_manageClientsMouseExited

    private void pnl_manageClientsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_manageClientsMouseEntered
        Color clr = new Color(255, 51, 51);
        pnl_manageClients.setBackground(clr);
    }//GEN-LAST:event_pnl_manageClientsMouseEntered

    private void pnl_manageClientsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_manageClientsMouseExited
        Color clr = new Color(51,51,51);
        pnl_manageClients.setBackground(clr);
    }//GEN-LAST:event_pnl_manageClientsMouseExited

    private void lbl_allocateTrainersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_allocateTrainersMouseEntered
        Color clr = new Color(255, 51, 51);
        pnl_allocateTrainers.setBackground(clr);
    }//GEN-LAST:event_lbl_allocateTrainersMouseEntered

    private void lbl_allocateTrainersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_allocateTrainersMouseExited
        Color clr = new Color(51,51,51);
        pnl_allocateTrainers.setBackground(clr);
    }//GEN-LAST:event_lbl_allocateTrainersMouseExited

    private void pnl_allocateTrainersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_allocateTrainersMouseEntered
        Color clr = new Color(255, 51, 51);
        pnl_allocateTrainers.setBackground(clr);
    }//GEN-LAST:event_pnl_allocateTrainersMouseEntered

    private void pnl_allocateTrainersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_allocateTrainersMouseExited
        Color clr = new Color(51,51,51);
        pnl_allocateTrainers.setBackground(clr);
    }//GEN-LAST:event_pnl_allocateTrainersMouseExited

    private void lbl_viewRecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_viewRecordMouseEntered
        Color clr = new Color(255, 51, 51);
        pnl_viewRecord.setBackground(clr);
    }//GEN-LAST:event_lbl_viewRecordMouseEntered

    private void lbl_viewRecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_viewRecordMouseExited
        Color clr = new Color(51,51,51);
        pnl_viewRecord.setBackground(clr);
    }//GEN-LAST:event_lbl_viewRecordMouseExited

    private void pnl_viewRecordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_viewRecordMouseEntered
        Color clr = new Color(255, 51, 51);
        pnl_viewRecord.setBackground(clr);
    }//GEN-LAST:event_pnl_viewRecordMouseEntered

    private void pnl_viewRecordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_viewRecordMouseExited
        Color clr = new Color(51,51,51);
        pnl_viewRecord.setBackground(clr);
    }//GEN-LAST:event_pnl_viewRecordMouseExited

    private void lbl_defaulterListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_defaulterListMouseEntered
        Color clr = new Color(255, 51, 51);
        pnl_defaulterList.setBackground(clr);
    }//GEN-LAST:event_lbl_defaulterListMouseEntered

    private void lbl_defaulterListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_defaulterListMouseExited
        Color clr = new Color(51,51,51);
        pnl_defaulterList.setBackground(clr);
    }//GEN-LAST:event_lbl_defaulterListMouseExited

    private void pnl_defaulterListMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_defaulterListMouseEntered
        Color clr = new Color(255, 51, 51);
        pnl_defaulterList.setBackground(clr);
    }//GEN-LAST:event_pnl_defaulterListMouseEntered

    private void pnl_defaulterListMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_defaulterListMouseExited
        Color clr = new Color(51,51,51);
        pnl_defaulterList.setBackground(clr);
    }//GEN-LAST:event_pnl_defaulterListMouseExited

    private void lbl_allocateTrainersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_allocateTrainersMouseClicked
        AllocateTrainer at = new AllocateTrainer();
        at.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_allocateTrainersMouseClicked

    private void lbl_manageClientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_manageClientsMouseClicked
        ManageClients mcl = new ManageClients();
        mcl.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_manageClientsMouseClicked

    private void lbl_viewRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_viewRecordMouseClicked
        ViewAllRecords var = new ViewAllRecords();
        var.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_viewRecordMouseClicked

    private void lbl_defaulterListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_defaulterListMouseClicked
        DefaulterList df = new DefaulterList();
        df.setVisible(true);
        dispose();
    }//GEN-LAST:event_lbl_defaulterListMouseClicked

    private void lbl_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseEntered
        Color clr = new Color(255, 51, 51);
        pnl_exit.setBackground(clr);
    }//GEN-LAST:event_lbl_exitMouseEntered

    private void lbl_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseExited
        Color clr = new Color(51,51,51);
        pnl_exit.setBackground(clr);
    }//GEN-LAST:event_lbl_exitMouseExited

    private void pnl_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_exitMouseEntered
        Color clr = new Color(255, 51, 51);
        pnl_exit.setBackground(clr);
    }//GEN-LAST:event_pnl_exitMouseEntered

    private void pnl_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_exitMouseExited
        Color clr = new Color(51,51,51);
        pnl_exit.setBackground(clr);
    }//GEN-LAST:event_pnl_exitMouseExited

    private void lbl_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lbl_exitMouseClicked

    private void ClientTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientTableMouseClicked
        // TODO add your handling code here:
       

    }//GEN-LAST:event_ClientTableMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void btn6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn6MouseClicked
        // TODO add your handling code here:
        login l=new login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ClientTable;
    private javax.swing.JPanel btn6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_allocateTrainers;
    private javax.swing.JLabel lbl_defaulterList;
    private javax.swing.JLabel lbl_exit;
    private javax.swing.JLabel lbl_manageClients;
    private javax.swing.JLabel lbl_manageCoaches;
    private javax.swing.JLabel lbl_noOfClients;
    private javax.swing.JLabel lbl_noOfTrainers;
    private javax.swing.JLabel lbl_viewRecord;
    private javax.swing.JPanel pnl_allocateTrainers;
    private javax.swing.JPanel pnl_defaulterList;
    private javax.swing.JPanel pnl_exit;
    private javax.swing.JPanel pnl_manageClients;
    private javax.swing.JPanel pnl_manageCoaches;
    private javax.swing.JPanel pnl_viewRecord;
    // End of variables declaration//GEN-END:variables
}
