/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gym_management_system;

import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
/**
 *
 * @author Rushabh Warke
 */
public class ManageClients extends javax.swing.JFrame {

    /**
     * Creates new form ManageClients
     */
    Connection con=null;
    ResultSet rs=null;
    PreparedStatement ps=null;
    String clientName, mobile, clientId, Gender;

    DefaultTableModel model;

    public ManageClients() {
        initComponents();
         con=DBconnection.getconnection();
        setClientDetails();
    }

    public void setClientDetails(){
        try
        {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM `client_details`");

            while(rs.next())
            {
                int clientId = rs.getInt("client_id");
                String clientName = rs.getString("client_name");
                String mobile = rs.getString("mobile");
                String Gender = rs.getString("gender");

                Object[] obj = {clientId, clientName, mobile, Gender};
                model = (DefaultTableModel)ClientTable.getModel();
                model.addRow(obj);

            }
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
    }

    public boolean addclient()
    {
        boolean isAdded = false;
        clientId = ClientID.getText();
        clientName =CName.getText();
        mobile = CMobile.getText();
        Gender = CGender.getText();

        try
        {

            String sql = "INSERT INTO `client_details`(`client_id`, `client_name`, `mobile`, `gender`) VALUES (?,?,?,?)";
            PreparedStatement pst = con.prepareStatement(sql);

            pst.setString(1, clientId);
            pst.setString(2, clientName);
            pst.setString(3, mobile);
            pst.setString(4, Gender);

            int rowCount = pst.executeUpdate();
            if(rowCount>0)
            {
                isAdded = true;
            }
            else
            {
                isAdded = false;
            }
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
        return isAdded;
    }

    public boolean updateclient()
    {
        boolean isUpdated = false;
        clientId = ClientID.getText();
        clientName = CName.getText();
        mobile = CMobile.getText();
        Gender = CGender.getText();

        try
        {
           String sql = "UPDATE `client_details` SET `client_id`=?,`client_name`=?,`mobile`=?,`gender`=? WHERE `client_id`=?";
            PreparedStatement pst = con.prepareStatement(sql);
             pst.setString(1, clientId);
            pst.setString(2, clientName);
            pst.setString(3, mobile);
            pst.setString(4, Gender);
            pst.setString(5, clientId);

            int rowCount = pst.executeUpdate();
            if (rowCount>0)
            {
               isUpdated = true;
            }
            else
            {
                isUpdated = false;
            }
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
        return isUpdated;
    }

    public boolean deleteClient()
    {
        boolean isDeleted = false;
        clientId = ClientID.getText();

        try
        {
            String sql = "DELETE FROM `client_details` WHERE `client_id`=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, clientId);

            int rowCount = pst.executeUpdate();
            if(rowCount>0)
            {
                isDeleted = true;
            }
            else
            {
                isDeleted = false;
            }
        }
        catch (Exception e)
        {
            e.printStackTrace();
        }
        return isDeleted;
    }

    public void clearTable()
    {
        DefaultTableModel model = (DefaultTableModel) ClientTable.getModel();
        model.setRowCount(0);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        CName = new javax.swing.JTextField();
        CMobile = new javax.swing.JTextField();
        ClientID = new javax.swing.JTextField();
        CGender = new javax.swing.JTextField();
        CBackBtn = new javax.swing.JButton();
        CAddBtn = new javax.swing.JButton();
        CUpdateBtn = new javax.swing.JButton();
        CDeleteBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ClientTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Client Id:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 130, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym_management_system/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 50, 50));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym_management_system/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 50, 50));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Name:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 130, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym_management_system/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 50, 50));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Mobile:");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 130, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gym_management_system/icons/icons/icons8_Account_50px.png"))); // NOI18N
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 50, 50));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Gender:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 550, 130, -1));

        CName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CName.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        jPanel2.add(CName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 370, 50));

        CMobile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CMobile.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        jPanel2.add(CMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 370, 50));

        ClientID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ClientID.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        ClientID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientIDActionPerformed(evt);
            }
        });
        jPanel2.add(ClientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 370, 50));

        CGender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CGender.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        jPanel2.add(CGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 580, 370, 50));

        CBackBtn.setBackground(new java.awt.Color(255, 0, 0));
        CBackBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CBackBtn.setForeground(new java.awt.Color(255, 255, 255));
        CBackBtn.setText("Back");
        CBackBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBackBtnActionPerformed(evt);
            }
        });
        jPanel2.add(CBackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 30));

        CAddBtn.setBackground(new java.awt.Color(0, 204, 0));
        CAddBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CAddBtn.setForeground(new java.awt.Color(255, 255, 255));
        CAddBtn.setText("ADD");
        CAddBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        CAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAddBtnActionPerformed(evt);
            }
        });
        jPanel2.add(CAddBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 740, 90, 30));

        CUpdateBtn.setBackground(new java.awt.Color(0, 0, 204));
        CUpdateBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CUpdateBtn.setForeground(new java.awt.Color(255, 255, 255));
        CUpdateBtn.setText("Update");
        CUpdateBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        CUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CUpdateBtnActionPerformed(evt);
            }
        });
        jPanel2.add(CUpdateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 740, 90, 30));

        CDeleteBtn.setBackground(new java.awt.Color(255, 0, 0));
        CDeleteBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CDeleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        CDeleteBtn.setText("Delete");
        CDeleteBtn.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        CDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CDeleteBtnActionPerformed(evt);
            }
        });
        jPanel2.add(CDeleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 740, 90, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 830));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 153));
        jLabel1.setText("Manage Clients");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 150, 260, 50));

        jPanel4.setBackground(new java.awt.Color(255, 0, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 300, 5));

        jScrollPane1.setBackground(new java.awt.Color(255, 153, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));

        ClientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Mobile", "Gender"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ClientTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClientTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ClientTable);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 230, 620, 170));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("X");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 20, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 960, 820));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1724, 824));
        jPanel1.getAccessibleContext().setAccessibleName("");

        setSize(new java.awt.Dimension(1543, 824));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rSMaterialButtonRectangle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle1ActionPerformed

    }//GEN-LAST:event_rSMaterialButtonRectangle1ActionPerformed

    private void rSMaterialButtonRectangle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_rSMaterialButtonRectangle2ActionPerformed

    private void tbl_clientDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_clientDetailsMouseClicked

    }//GEN-LAST:event_tbl_clientDetailsMouseClicked

    private void btn_addClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addClientActionPerformed

    }//GEN-LAST:event_btn_addClientActionPerformed

    private void btn_clientUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clientUpdateMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_clientUpdateMouseEntered

    private void btn_clientUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clientUpdateMouseClicked

    }//GEN-LAST:event_btn_clientUpdateMouseClicked

    private void btn_clientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clientNameActionPerformed

    }//GEN-LAST:event_btn_clientNameActionPerformed

    private void ClientIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClientIDActionPerformed

    private void ClientTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientTableMouseClicked
        // TODO add your handling code here:
        int rowNo = ClientTable.getSelectedRow();
        TableModel model = ClientTable.getModel();

        ClientID.setText(model.getValueAt(rowNo, 0).toString());
        CName.setText(model.getValueAt(rowNo, 1).toString());
        CMobile.setText(model.getValueAt(rowNo, 2).toString());
        CGender.setText(model.getValueAt(rowNo, 3).toString());


    }//GEN-LAST:event_ClientTableMouseClicked

    private void CBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBackBtnActionPerformed
        // TODO add your handling code here:

        HomePage hm = new HomePage();
        hm.setVisible(true);
        dispose();
    }//GEN-LAST:event_CBackBtnActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void CAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAddBtnActionPerformed
        // TODO add your handling code here:
        if(addclient()==true)
        {
            JOptionPane.showMessageDialog(this, "Client has Added");
            clearTable();
            setClientDetails();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Client has not Added");
        }
    }//GEN-LAST:event_CAddBtnActionPerformed

    private void CUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CUpdateBtnActionPerformed
        // TODO add your handling code here:
        if(updateclient()==true)
        {
            JOptionPane.showMessageDialog(this, "Updated Successfully");
            clearTable();
            setClientDetails();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Try Again");
        }

    }//GEN-LAST:event_CUpdateBtnActionPerformed

    private void CDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CDeleteBtnActionPerformed
        // TODO add your handling code here:
        if(deleteClient()==true)
        {
            JOptionPane.showMessageDialog(this, "Deleted Successfully");
            clearTable();
            setClientDetails();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Try Again");
        }
    }//GEN-LAST:event_CDeleteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageClients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageClients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageClients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageClients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageClients().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CAddBtn;
    private javax.swing.JButton CBackBtn;
    private javax.swing.JButton CDeleteBtn;
    private javax.swing.JTextField CGender;
    private javax.swing.JTextField CMobile;
    private javax.swing.JTextField CName;
    private javax.swing.JButton CUpdateBtn;
    private javax.swing.JTextField ClientID;
    private javax.swing.JTable ClientTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
